[[redirects]]
  from = "/api/categories/"
  to = "https://recipe-book-app-react.herokuapp.com/api/categories/"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/recipes/"
  to = "https://recipe-book-app-react.herokuapp.com/api/recipes/"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/recipes/*"
  to = "https://recipe-book-app-react.herokuapp.com/api/recipes/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/"
  status = 200