export const RECIPES_LIST_REQUEST = 'RECIPES_LIST_REQUEST'
export const RECIPES_LIST_SUCCESS = 'RECIPES_LIST_SUCCESS'
export const RECIPES_LIST_FAIL = 'RECIPES_LIST_FAIL'

export const RECIPE_DETAILS_REQUEST = 'RECIPE_DETAILS_REQUEST'
export const RECIPE_DETAILS_SUCCESS = 'RECIPE_DETAILS_SUCCESS'
export const RECIPE_DETAILS_FAIL = 'RECIPE_DETAILS_FAIL'